/**
 * Demo CV Data — Dr. Maya Thompson, MD, PhD, FRCP, FACC
 *
 * All data is completely fictional.
 * Used for admin learning/preview only.
 * Tagged with isDemo=true for safe removal.
 */

export const DEMO_IDENTITY = {
  cvFirstName: "Maya",
  cvLastName: "Thompson",
  cvPostNominals: "MD, PhD, FRCP, FACC",
  cvProfessionalTitle: "Consultant Cardiologist & Senior Clinical Researcher",
  cvSpecialty: "Interventional & Structural Heart Disease",
  cvEmail: "maya.thompson@example.invalid",
  cvPhone: "+44-20-7946-0001",
  cvCity: "London",
  cvRegion: "England",
  cvCountry: "United Kingdom",
  cvWebsite: "https://mayathompson.example.invalid",
  cvLinkedin: "https://linkedin.com/in/mayathompson-demo",
}

export const DEMO_ENTRIES = [
  // ── 1. Professional Identity ──
  {
    sectionKey: "professional_identity",
    title: "Consultant Cardiologist & Senior Clinical Researcher",
    subtitle: "MD, PhD, FRCP, FACC",
    institution: "Northbridge Heart Institute",
    department: "Interventional Cardiology",
    location: "London, United Kingdom",
    description:
      "Internationally recognised interventional cardiologist with dual expertise in complex coronary interventions and structural heart disease. Over 15 years of clinical practice spanning the UK, Canada, and France. Published researcher with 50+ peer-reviewed publications and leadership of multi-centre clinical trials. Fellow of the Royal College of Physicians (UK) and the American College of Cardiology.",
    bullets: "",
    email: "maya.thompson@example.invalid",
    phone: "+44-20-7946-0001",
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 2. Executive Summary ──
  {
    sectionKey: "executive_summary",
    title: "Professional Summary",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Dr. Maya Thompson is a consultant cardiologist and senior clinical researcher at Northbridge Heart Institute, London. She holds an MD from Northbridge University (2010, with honours) and a PhD in Cardiovascular Sciences from Westland University (2013). Her clinical focus encompasses complex percutaneous coronary interventions, transcatheter valve therapies, and left atrial appendage closure. She has led or co-led over £1.2 million in competitive research funding and authored 50+ peer-reviewed papers in high-impact journals including the European Heart Journal, JACC Cardiovascular Interventions, and The Lancet. Dr. Thompson serves on the editorial boards of three major cardiology journals and is an invited speaker at international cardiovascular meetings. She is committed to advancing patient care through evidence-based medicine, innovative procedural techniques, and global training initiatives.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 3. Current Clinical Appointments ──
  {
    sectionKey: "current_clinical_appointments",
    title: "Consultant Interventional Cardiologist",
    subtitle: "DEMO-APPT-CLIN-001",
    institution: "Northbridge Heart Institute",
    department: "Interventional Cardiology",
    location: "London, United Kingdom",
    description:
      "Lead consultant for complex coronary interventions and structural heart programme. Responsible for 800+ PCI procedures annually, including chronic total occlusions, left main stenting, and TAVI.",
    bullets:
      "Perform complex PCI including CTO, left main, and bifurcation interventions\nLead TAVI, mitral clip, and LAA closure programmes\nChair monthly interventional case review meetings\nSupervise and mentor 4 interventional cardiology fellows",
    email: "",
    phone: "",
    startDate: "2019-03-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {
      description: { public: true, pdf: true, docx: true },
    },
  },
  {
    sectionKey: "current_clinical_appointments",
    title: "Consultant Cardiologist — General Cardiology",
    subtitle: "DEMO-APPT-CLIN-002",
    institution: "Northbridge Heart Institute",
    department: "General Cardiology",
    location: "London, United Kingdom",
    description:
      "Outpatient general cardiology clinics two days per week. Expertise in heart failure, arrhythmia management, and preventive cardiology.",
    bullets:
      "Run dedicated heart failure clinic with multidisciplinary team\nSee 25–30 patients per clinic session\nCo-lead chest pain rapid-access clinic",
    email: "",
    phone: "",
    startDate: "2019-03-01",
    isCurrent: true,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 4. Current Academic Appointments ──
  {
    sectionKey: "current_academic_appointments",
    title: "Honorary Senior Clinical Lecturer",
    subtitle: "DEMO-APPT-ACAD-001",
    institution: "Westland University",
    department: "Department of Cardiovascular Sciences",
    location: "London, United Kingdom",
    description:
      "Academic appointment in the Division of Cardiovascular Sciences. Deliver undergraduate and postgraduate lectures, supervise doctoral students, and lead research projects within the university's cardiovascular research group.",
    bullets:
      "Lead Year 5 Cardiology Module — 80 students per year\nSupervise 3 PhD candidates and 2 postdoctoral fellows\nCo-director of the Cardiovascular Research Translation Programme",
    email: "",
    phone: "",
    startDate: "2020-09-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 5. Medical Licensure ──
  {
    sectionKey: "medical_licensure",
    title: "Full Registration with Licence to Practise",
    subtitle: "SECRET-LICENSE-98765",
    institution: "General Medical Council",
    department: "",
    location: "United Kingdom",
    description:
      "Full registration with licence to practise. In continuous good standing since 2010.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 0,
    fieldVisibility: { subtitle: { public: false, pdf: true, docx: false } },
  },
  {
    sectionKey: "medical_licensure",
    title: "Specialist Registration — Cardiology",
    subtitle: "DEMO-LIC-UK-002",
    institution: "General Medical Council",
    department: "Specialist Register",
    location: "United Kingdom",
    description:
      "Included on the Specialist Register for Cardiology since 2017.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 1,
    fieldVisibility: { subtitle: { public: false, pdf: true, docx: false } },
  },
  {
    sectionKey: "medical_licensure",
    title: "Licence to Practise — Province of Ontario",
    subtitle: "DEMO-LIC-CA-001",
    institution: "College of Physicians and Surgeons of Ontario",
    department: "",
    location: "Canada",
    description:
      "Independent practice licence, Province of Ontario. Active during residency and fellowship (2011–2018). Currently inactive.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 2,
    fieldVisibility: { subtitle: { public: false, pdf: true, docx: false } },
  },

  // ── 6. Board Certification ──
  {
    sectionKey: "board_certification",
    title: "Board Certified — Internal Medicine",
    subtitle: "CERT-SECRET-001",
    institution: "Royal College of Physicians and Surgeons of Canada",
    department: "Internal Medicine",
    location: "Canada",
    description:
      "Certified specialist in Internal Medicine, FRCPC. Achieved 2014.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2014-06-30",
    sortOrder: 0,
    fieldVisibility: { subtitle: { public: false, pdf: true, docx: false } },
  },
  {
    sectionKey: "board_certification",
    title: "Board Certified — Cardiovascular Disease",
    subtitle: "DEMO-BOARD-CARD-001",
    institution: "American Board of Internal Medicine",
    department: "Cardiovascular Disease",
    location: "United States",
    description:
      "Board certified in Cardiovascular Disease. Maintains active certification.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2018-09-15",
    sortOrder: 1,
    fieldVisibility: { subtitle: { public: false, pdf: true, docx: false } },
  },

  // ── 7. Professional Certifications ──
  {
    sectionKey: "professional_certifications",
    title: "Fellow of the Royal College of Physicians",
    subtitle: "FRCP (UK)",
    institution: "Royal College of Physicians",
    department: "",
    location: "United Kingdom",
    description:
      "Elected Fellow of the Royal College of Physicians (London) in recognition of contributions to cardiovascular medicine and medical education.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2021-03-15",
    sortOrder: 0,
    fieldVisibility: { subtitle: { public: true, pdf: true, docx: true } },
  },
  {
    sectionKey: "professional_certifications",
    title: "Fellow of the American College of Cardiology",
    subtitle: "FACC",
    institution: "American College of Cardiology",
    department: "",
    location: "United States",
    description:
      "Elected Fellow of the American College of Cardiology for contributions to interventional cardiology research and clinical practice.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2020-06-01",
    sortOrder: 1,
    fieldVisibility: { subtitle: { public: true, pdf: true, docx: true } },
  },
  {
    sectionKey: "professional_certifications",
    title: "European Board of Cardiovascular Medicine — Interventional Cardiology",
    subtitle: "PRO-CERT-SECRET-002",
    institution: "European Board for Cardiology",
    department: "",
    location: "European Union",
    description:
      "Certified in Interventional Cardiology by the European Board for Cardiology under the UEMS.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2019-05-20",
    sortOrder: 2,
    fieldVisibility: { subtitle: { public: false, pdf: false, docx: true } },
  },

  // ── 8. Medical Education ──
  {
    sectionKey: "medical_education",
    title: "Doctor of Medicine (MD)",
    subtitle: "",
    institution: "Northbridge University",
    department: "Faculty of Medicine",
    location: "London, United Kingdom",
    description:
      "Graduated with First Class Honours. Thesis: 'Novel Biomarkers for Early Detection of Myocardial Injury in Acute Coronary Syndromes — A Prospective Cohort Study.' Dean's List 2007–2010. Winner of the Sir William Osler Prize for Clinical Excellence.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2004-09-01",
    endDate: "2010-06-30",
    isCurrent: false,
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 9. Other Degrees ──
  {
    sectionKey: "other_degrees",
    title: "Doctor of Philosophy (PhD) — Cardiovascular Sciences",
    subtitle: "",
    institution: "Westland University",
    department: "Institute of Cardiovascular Sciences",
    location: "London, United Kingdom",
    description:
      "Awarded for thesis: 'Transcatheter Aortic Valve Haemodynamics — In Vitro Modelling and Clinical Correlation.' Supervised by Prof. Sir James Hartley. Published 6 papers from doctoral work.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2010-10-01",
    endDate: "2013-09-30",
    isCurrent: false,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "other_degrees",
    title: "Master of Research (MRes) — Biomedical Sciences",
    subtitle: "",
    institution: "Northbridge University",
    department: "Faculty of Medicine",
    location: "London, United Kingdom",
    description:
      "Intercalated degree during medical training. Distinction. Project: 'Endothelial Function and Arterial Stiffness in Hypertensive Patients.'",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2007-09-01",
    endDate: "2008-06-30",
    isCurrent: false,
    sortOrder: 1,
    fieldVisibility: {},
  },
  {
    sectionKey: "other_degrees",
    title: "Bachelor of Science (BSc) — Pharmacology",
    subtitle: "",
    institution: "Northbridge University",
    department: "Faculty of Life Sciences",
    location: "London, United Kingdom",
    description:
      "First Class Honours. Intercalated BSc during medical school.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2006-09-01",
    endDate: "2007-06-30",
    isCurrent: false,
    sortOrder: 2,
    fieldVisibility: {},
  },

  // ── 10. Internship ──
  {
    sectionKey: "internship",
    title: "Foundation Year 1 — Foundation Programme",
    subtitle: "",
    institution: "Northbridge University Hospitals NHS Trust",
    department: "General Surgery / Emergency Medicine / Geriatric Medicine",
    location: "London, United Kingdom",
    description:
      "Rotational internship as part of the UK Foundation Programme. Gained broad clinical experience across surgical, emergency, and medical disciplines.",
    bullets:
      "Emergency Medicine — managed 200+ acute admissions\nGeneral Surgery — assisted in 50+ surgical procedures\nGeriatric Medicine — comprehensive geriatric assessments",
    email: "",
    phone: "",
    startDate: "2010-08-01",
    endDate: "2011-07-31",
    isCurrent: false,
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 11. Residency ──
  {
    sectionKey: "residency",
    title: "Internal Medicine Residency",
    subtitle: "",
    institution: "Metropolitan General Hospital",
    department: "Department of Internal Medicine",
    location: "Toronto, Canada",
    description:
      "Three-year categorical residency in Internal Medicine. Chief Resident in final year. Developed a strong interest in cardiovascular medicine during coronary care unit rotations. Achieved fellowship of the Royal College of Physicians and Surgeons of Canada (FRCPC).",
    bullets:
      "Chief Resident — coordinated schedules and teaching for 42 residents\nCCU rotation — managed acute coronary syndromes and cardiogenic shock\nQuality improvement project: reduced door-to-ECG time by 40%\nAchieved above-programme-average pass rate on Royal College examinations",
    email: "",
    phone: "",
    startDate: "2011-08-01",
    endDate: "2014-06-30",
    isCurrent: false,
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 12. Fellowship ──
  {
    sectionKey: "fellowship",
    title: "General Cardiology Fellowship",
    subtitle: "DEMO-FELL-CARD-001",
    institution: "Northbridge Heart Institute",
    department: "Division of Cardiology",
    location: "London, United Kingdom",
    description:
      "Three-year general cardiology fellowship encompassing non-invasive imaging, electrophysiology, heart failure, and interventional cardiology. Completed 600+ diagnostic catheterisations.",
    bullets:
      "Echocardiography — acquired Level 3 certification\nNuclear cardiology — performed and interpreted 300+ myocardial perfusion scans\nElectrophysiology rotation — assisted in 40+ ablation procedures",
    email: "",
    phone: "",
    startDate: "2014-09-01",
    endDate: "2017-08-31",
    isCurrent: false,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "fellowship",
    title: "Interventional Cardiology Fellowship",
    subtitle: "DEMO-FELL-INT-001",
    institution: "Northbridge Heart Institute",
    department: "Interventional Cardiology",
    location: "London, United Kingdom",
    description:
      "Two-year advanced interventional cardiology fellowship. Trained in complex coronary interventions, rotational atherectomy, intravascular imaging, and structural heart procedures. Completed 800+ supervised PCI procedures.",
    bullets:
      "Rotational atherectomy and intravascular lithotripsy\nLeft main and bifurcation stenting with IVUS guidance\nStructural heart — TAVI and mitral clip procedures\nSelected as fellow of the year 2018",
    email: "",
    phone: "",
    startDate: "2017-09-01",
    endDate: "2019-08-31",
    isCurrent: false,
    sortOrder: 1,
    fieldVisibility: {},
  },
  {
    sectionKey: "fellowship",
    title: "Structural Heart Disease Fellowship",
    subtitle: "DEMO-FELL-SH-001",
    institution: "International Cardiac Centre",
    department: "Structural Heart Programme",
    location: "Paris, France",
    description:
      "Six-month advanced fellowship in structural heart disease at a high-volume European centre. Performed 80+ transcatheter valve procedures including TAVI, mitral repair, and tricuspid interventions.",
    bullets:
      "TAVI — transcatheter aortic valve implantation (balloon-expandable and self-expanding)\nMitraClip and PASCAL transcatheter mitral repair\nLeft atrial appendage occlusion (Watchman and Amulet devices)\nTricuspid clip procedures — emerging therapy",
    email: "",
    phone: "",
    startDate: "2019-09-01",
    endDate: "2020-02-28",
    isCurrent: false,
    sortOrder: 2,
    fieldVisibility: {},
  },

  // ── 13. Postdoctoral Training ──
  {
    sectionKey: "postdoctoral_training",
    title: "Postdoctoral Research Fellow — Cardiovascular Imaging",
    subtitle: "",
    institution: "Westland University",
    department: "Institute of Cardiovascular Sciences",
    location: "London, United Kingdom",
    description:
      "Two-year postdoctoral research position focused on cardiovascular imaging and computational modelling of transcatheter heart valves. Published 4 papers from this work.",
    bullets:
      "Developed finite element model of transcatheter aortic valve deployment\nCollaborated with biomedical engineering team on prosthetic valve haemodynamics\nPresented findings at EuroPCR and ACC Annual Scientific Sessions",
    email: "",
    phone: "",
    startDate: "2013-10-01",
    endDate: "2014-08-31",
    isCurrent: false,
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 14. Advanced Training ──
  {
    sectionKey: "advanced_training",
    title: "Level 3 Echocardiography Certification",
    subtitle: "DEMO-ADV-ECHO-001",
    institution: "British Society of Echocardiography",
    department: "",
    location: "United Kingdom",
    description:
      "Accredited Level 3 (transoesophageal and structural heart) echocardiography certification.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2018-11-01",
    sortOrder: 0,
    fieldVisibility: { subtitle: { public: false, pdf: true, docx: false } },
  },
  {
    sectionKey: "advanced_training",
    title: "Certification in Cardiac CT — Level 2",
    subtitle: "DEMO-ADV-CCT-001",
    institution: " Society of Cardiovascular Computed Tomography",
    department: "",
    location: "United States",
    description:
      "Board certification in cardiac computed tomography. Competent in coronary CTA, TAVI planning, and structural heart CT.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2020-04-15",
    sortOrder: 1,
    fieldVisibility: { subtitle: { public: false, pdf: true, docx: false } },
  },

  // ── 15. Clinical Experience ──
  {
    sectionKey: "clinical_experience",
    title: "Consultant Interventional Cardiologist",
    subtitle: "Complex PCI & Structural Heart",
    institution: "Northbridge Heart Institute",
    department: "Interventional Cardiology",
    location: "London, United Kingdom",
    description:
      "Lead consultant for complex coronary interventions and structural heart programme. Manages a busy interventional caseload of 800+ procedures annually. Established the structural heart disease programme in 2020, which has since treated 350+ patients.",
    bullets:
      "Perform complex PCI including chronic total occlusions, left main, and bifurcation lesions\nLead TAVI, mitral clip, and LAA closure programmes\nIntroduced intravascular imaging protocols reducing restenosis rates by 15%\nSupervise and train 4 interventional cardiology fellows per year\n24/7 primary PCI rota for ST-elevation myocardial infarction",
    email: "",
    phone: "",
    startDate: "2019-03-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {
      description: { public: true, pdf: true, docx: true },
    },
  },
  {
    sectionKey: "clinical_experience",
    title: "Locum Consultant Cardiologist",
    subtitle: "",
    institution: "Royal Metropolitan Hospital",
    department: "Cardiology",
    location: "Birmingham, United Kingdom",
    description:
      "Six-month locum consultant position providing general and interventional cardiology cover. Managed heart failure clinic and chest pain service.",
    bullets:
      "Ran heart failure clinic with 80+ patients\nDelivered acute cardiology on-call cover (1:6 rota)\nParticipated in TAVI multidisciplinary team meetings",
    email: "",
    phone: "",
    startDate: "2018-09-01",
    endDate: "2019-02-28",
    isCurrent: false,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 16. Clinical Expertise ──
  {
    sectionKey: "clinical_expertise",
    title: "Complex Coronary Intervention",
    subtitle: "Expert",
    institution: "",
    department: "",
    location: "",
    description:
      "Chronic total occlusions, left main disease, bifurcation lesions, rotational atherectomy, intravascular lithotripsy. Over 3,000 lifetime PCI procedures.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "clinical_expertise",
    title: "Structural Heart Interventions",
    subtitle: "Expert",
    institution: "",
    department: "",
    location: "",
    description:
      "Transcatheter aortic valve implantation (TAVI), MitraClip, left atrial appendage closure, patent foramen ovale closure, tricuspid clip procedures.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 1,
    fieldVisibility: {},
  },
  {
    sectionKey: "clinical_expertise",
    title: "Cardiac Imaging",
    subtitle: "Advanced",
    institution: "",
    department: "",
    location: "",
    description:
      "Transthoracic and transoesophageal echocardiography (Level 3), cardiac CT (Level 2), cardiac MRI (Level 1), intravascular imaging (IVUS, OCT).",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 2,
    fieldVisibility: {},
  },
  {
    sectionKey: "clinical_expertise",
    title: "Heart Failure Management",
    subtitle: "Proficient",
    institution: "",
    department: "",
    location: "",
    description:
      "Advanced heart failure, device therapy (CRT, LVAD assessment), palliative care integration, multidisciplinary heart failure clinic.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 3,
    fieldVisibility: {},
  },

  // ── 17. Procedures & Skills ──
  {
    sectionKey: "procedures_skills",
    title: "Percutaneous Coronary Intervention",
    subtitle: "Expert — 3,000+ lifetime procedures",
    institution: "",
    department: "",
    location: "",
    description:
      "Complex PCI including CTO (retrograde and antegrade), left main, bifurcation (DK crush, culotte), rotational atherectomy, intravascular lithotripsy. IVUS and OCT guided.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "procedures_skills",
    title: "Transcatheter Aortic Valve Implantation (TAVI)",
    subtitle: "Expert — 200+ procedures",
    institution: "",
    department: "",
    location: "",
    description:
      "Transfemoral and transapical approaches. Balloon-expandable (Edwards SAPIEN) and self-expanding (Medtronic CoreValve) valves. Complex anatomies including bicuspid valves.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 1,
    fieldVisibility: {},
  },
  {
    sectionKey: "procedures_skills",
    title: "MitraClip / Transcatheter Mitral Repair",
    subtitle: "Expert — 60+ procedures",
    institution: "",
    department: "",
    location: "",
    description:
      "MitraClip NTS and XTR. PASCAL transcatheter mitral repair system. Echocardiography-guided deployment.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 2,
    fieldVisibility: {},
  },
  {
    sectionKey: "procedures_skills",
    title: "Left Atrial Appendage Occlusion",
    subtitle: "Proficient — 40+ procedures",
    institution: "",
    department: "",
    location: "",
    description:
      "Watchman and Watchman FLX devices. Amulet device. TEE-guided deployment and procedural planning.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 3,
    fieldVisibility: {},
  },
  {
    sectionKey: "procedures_skills",
    title: "Diagnostic Cardiac Catheterisation",
    subtitle: "Expert — 2,000+ procedures",
    institution: "",
    department: "",
    location: "",
    description:
      "Right and left heart catheterisation. Coronary angiography. Haemodynamic assessment. Intravascular imaging (IVUS, OCT).",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 4,
    fieldVisibility: {},
  },

  // ── 18. Hospital Appointments ──
  {
    sectionKey: "hospital_appointments",
    title: "Consultant Cardiologist — Northbridge Heart Institute",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Cardiology",
    location: "London, United Kingdom",
    description:
      "Substantive consultant post since March 2019. Clinical privileges in interventional cardiology, structural heart disease, cardiac imaging, and general cardiology.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2019-03-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "hospital_appointments",
    title: "Honorary Consultant Cardiologist — Royal London Hospital",
    subtitle: "",
    institution: "Royal London Hospital, Barts Health NHS Trust",
    department: "Cardiology",
    location: "London, United Kingdom",
    description:
      "Honorary appointment for teaching and research collaboration. Participate in weekly grand rounds and joint research seminars.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2020-01-01",
    isCurrent: true,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 19. Quality Improvement ──
  {
    sectionKey: "quality_improvement",
    title: "Reducing Door-to-Balloon Time for STEMI",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Interventional Cardiology",
    location: "London, United Kingdom",
    description:
      "Led quality improvement initiative to reduce door-to-balloon time for ST-elevation myocardial infarction from 92 minutes to 54 minutes through process re-engineering, pre-hospital ECG triage, and catheterisation laboratory activation protocols.",
    bullets:
      "Implemented pre-hospital ECG transmission and triage pathway\nEstablished 24/7 catheterisation laboratory activation protocol\nReduced median door-to-balloon time by 41%\nAchieved British Cardiovascular Intervention Society gold standard",
    email: "",
    phone: "",
    startDate: "2019-06-01",
    endDate: "2020-03-31",
    isCurrent: false,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "quality_improvement",
    title: "Intravascular Imaging Protocol for Complex PCI",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Interventional Cardiology",
    location: "London, United Kingdom",
    description:
      "Developed and implemented a standardised intravascular imaging protocol for complex PCI. Resulted in 15% reduction in target lesion revascularisation at 12 months.",
    bullets:
      "Introduced mandatory IVUS/OCT for left main and CTO interventions\nCreated standardised imaging acquisition and interpretation protocol\nReduced stent thrombosis rate from 1.8% to 0.9%\nPresented at EuroPCR 2023",
    email: "",
    phone: "",
    startDate: "2021-01-01",
    endDate: "2021-12-31",
    isCurrent: false,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 20. Clinical Audit ──
  {
    sectionKey: "clinical_audit",
    title: "Annual PCI Outcomes Audit — Northbridge Heart Institute",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Interventional Cardiology",
    location: "London, United Kingdom",
    description:
      "Lead auditor for annual percutaneous coronary intervention outcomes. Report to hospital clinical governance committee. Data submitted to national BCIS audit.",
    bullets:
      "Audit 800+ PCI procedures annually\nPresent findings to hospital clinical governance board\nBenchmark against national and international standards\nRecommend and implement changes based on audit findings",
    email: "",
    phone: "",
    startDate: "2020-01-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 21. Patient Safety ──
  {
    sectionKey: "patient_safety",
    title: "Structural Heart Programme — Patient Safety Lead",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Structural Heart Programme",
    location: "London, United Kingdom",
    description:
      "Patient safety lead for the structural heart disease programme. Responsible for incident reporting, root cause analysis, and implementation of safety protocols for TAVI, mitral clip, and LAA closure procedures.",
    bullets:
      "Developed structural heart procedural safety checklist\nImplemented weekly MDT review of all adverse events\nZero serious untoward incidents in 2023\nContributed to national NCEPOD review of TAVI outcomes",
    email: "",
    phone: "",
    startDate: "2020-06-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 22. Leadership ──
  {
    sectionKey: "leadership",
    title: "Director — Structural Heart Disease Programme",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Structural Heart Programme",
    location: "London, United Kingdom",
    description:
      "Established and direct the structural heart disease programme, encompassing TAVI, transcatheter mitral repair, LAA closure, and emerging transcatheter tricuspid therapies. Programme has treated 350+ patients since inception in 2020.",
    bullets:
      "Developed service specification and business case for structural heart programme\nBuilt multidisciplinary heart team of 18 members\nAchieved national accreditation within 2 years\nManaged programme budget of £2.5 million annually",
    email: "",
    phone: "",
    startDate: "2020-01-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "leadership",
    title: "Clinical Lead — Cardiac Catheterisation Laboratory",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Interventional Cardiology",
    location: "London, United Kingdom",
    description:
      "Clinical lead for the cardiac catheterisation laboratory, overseeing scheduling, equipment procurement, staff training, and quality assurance.",
    bullets:
      "Manage 3 cardiac catheterisation laboratories\nCoordinate rota for 12 interventional cardiologists\nIntroduced 3D rotational angiography and AI-assisted planning\nLed laboratory refurbishment project (£1.8 million)",
    email: "",
    phone: "",
    startDate: "2021-07-01",
    isCurrent: true,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 23. Academic Appointments ──
  {
    sectionKey: "academic_appointments",
    title: "Honorary Senior Clinical Lecturer",
    subtitle: "",
    institution: "Westland University",
    department: "Department of Cardiovascular Sciences",
    location: "London, United Kingdom",
    description:
      "Academic appointment in the Division of Cardiovascular Sciences. Deliver undergraduate and postgraduate lectures, supervise doctoral students, and lead research projects.",
    bullets:
      "Lead Year 5 Cardiology Module — 80 students per year\nSupervise 3 PhD candidates and 2 postdoctoral fellows\nCo-director of the Cardiovascular Research Translation Programme",
    email: "",
    phone: "",
    startDate: "2020-09-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "academic_appointments",
    title: "Visiting Professor of Interventional Cardiology",
    subtitle: "",
    institution: "University of Bordeaux",
    department: "Department of Cardiology",
    location: "Bordeaux, France",
    description:
      "Annual visiting professorship (2 weeks per year). Deliver lectures, participate in research collaboration, and provide procedural proctoring for structural heart interventions.",
    bullets:
      "Annual lecture series on structural heart interventions\nCollaborative research on TAVI haemodynamics with Bordeaux imaging lab\nProctoring for transcatheter mitral repair procedures",
    email: "",
    phone: "",
    startDate: "2022-01-01",
    isCurrent: true,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 24. Teaching Experience ──
  {
    sectionKey: "teaching_experience",
    title: "Year 5 Cardiology Module Lead",
    subtitle: "",
    institution: "Westland University",
    department: "Faculty of Medicine",
    location: "London, United Kingdom",
    description:
      "Lead the Year 5 Cardiology Module for medical students. Design curriculum, deliver lectures, and assess student competencies.",
    bullets:
      "80 students per year across 2 annual cohorts\nDeliver 12 lectures and 6 bedside teaching sessions\nDesign OSCE stations for summative assessment\nAverage student satisfaction rating: 4.7/5.0",
    email: "",
    phone: "",
    startDate: "2020-09-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "teaching_experience",
    title: "Interventional Cardiology Fellowship Programme — Clinical Supervisor",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Interventional Cardiology",
    location: "London, United Kingdom",
    description:
      "Clinical supervisor and programme director for interventional cardiology fellows. Provide procedural training, simulation-based education, and career mentorship.",
    bullets:
      "Supervise 4 fellows per year in complex PCI and structural heart procedures\nDesign simulation-based PCI training curriculum\nConduct quarterly workplace-based assessments\nPrepare fellows for independent practice and board certification",
    email: "",
    phone: "",
    startDate: "2019-09-01",
    isCurrent: true,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 25. Curriculum Leadership ──
  {
    sectionKey: "curriculum_leadership",
    title: "Cardiology Sub-Specialty Training Curriculum — External Examiner",
    subtitle: "",
    institution: "Joint Royal Colleges of Physicians Training Board (JRCPTB)",
    department: "",
    location: "United Kingdom",
    description:
      "External examiner for the UK Cardiology Specialty Training (ST4–ST7) curriculum. Review training standards, assess exit competencies, and advise on curriculum development.",
    bullets:
      "Review annual training reports for 5 regional training centres\nParticipate in Annual Review of Competence Progression (ARCP)\nAdvised on integration of structural heart training into curriculum\nAppointed 2022, reappointed 2024",
    email: "",
    phone: "",
    startDate: "2022-06-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 26. Mentoring ──
  {
    sectionKey: "mentoring",
    title: "Clinical Research Mentoring Programme",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Cardiology",
    location: "London, United Kingdom",
    description:
      "Formal mentoring programme for cardiology registrars and clinical research fellows. Provide career guidance, research mentorship, and procedural training advice.",
    bullets:
      "Currently mentoring 4 cardiology registrars and 2 clinical research fellows\nMonthly structured mentoring meetings\nSupport mentees in developing grant applications and publications\n3 mentees have progressed to consultant posts",
    email: "",
    phone: "",
    startDate: "2019-01-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 27. Research Experience ──
  {
    sectionKey: "research_experience",
    title: "Principal Investigator — COMPASS-PCI Registry",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Cardiovascular Research Unit",
    location: "London, United Kingdom",
    description:
      "Leading a prospective multicentre registry evaluating outcomes of complex PCI in elderly patients (n=2,500). Funded by the British Heart Foundation (£450,000).",
    bullets:
      "Designed protocol and obtained ethical approval\nRecruited 12 participating centres across the UK\nPresented interim analysis at ESC Congress 2024\nFinal 24-month results submitted to European Heart Journal",
    email: "",
    phone: "",
    startDate: "2021-01-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "research_experience",
    title: "Co-Investigator — OPTIMIZE-TAVI Randomised Controlled Trial",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Cardiovascular Research Unit",
    location: "London, United Kingdom",
    description:
      "Co-investigator for a multicentre randomised controlled trial comparing balloon-expandable versus self-expanding TAVI valves in intermediate-risk patients (n=800). Funded by NIHR HTA (£1.2 million).",
    bullets:
      "Lead site for UK recruitment — enrolled 120 patients\nCo-author on primary publication in The Lancet\nPresented 2-year outcomes at TCT 2023",
    email: "",
    phone: "",
    startDate: "2019-04-01",
    endDate: "2023-12-31",
    isCurrent: false,
    sortOrder: 1,
    fieldVisibility: {},
  },
  {
    sectionKey: "research_experience",
    title: "PhD Research — Transcatheter Aortic Valve Haemodynamics",
    subtitle: "",
    institution: "Westland University",
    department: "Institute of Cardiovascular Sciences",
    location: "London, United Kingdom",
    description:
      "Doctoral research combining computational modelling with clinical imaging to optimise transcatheter aortic valve deployment. Published 6 peer-reviewed papers.",
    bullets:
      "Developed novel finite element model of TAVI deployment\nValidated model against in vitro and clinical imaging data\nThesis awarded with no corrections\nSupervised by Prof. Sir James Hartley",
    email: "",
    phone: "",
    startDate: "2010-10-01",
    endDate: "2013-09-30",
    isCurrent: false,
    sortOrder: 2,
    fieldVisibility: {},
  },

  // ── 28. Research Interests ──
  {
    sectionKey: "research_interests",
    title: "Research Interests",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Complex coronary intervention outcomes in elderly patients\nTranscatheter valve haemodynamics and device optimisation\nIntravascular imaging-guided PCI and drug-eluting stent technology\nStructural heart disease — emerging transcatheter therapies\nArtificial intelligence in cardiovascular imaging\nGlobal cardiovascular health disparities",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 29. Grants ──
  {
    sectionKey: "grants",
    title: "COMPASS-PCI Registry — Outcomes of Complex PCI in Elderly Patients",
    subtitle: "BHF-2021-0456",
    institution: "British Heart Foundation",
    department: "",
    location: "United Kingdom",
    description: "£500,000",
    bullets:
      "Prospective multicentre registry of complex PCI outcomes in patients aged ≥75 years\nPrincipal Investigator\n3-year funding period (2021–2024)\n12 participating centres, 2,500 patients enrolled",
    email: "",
    phone: "",
    startDate: "2021-01-01",
    endDate: "2024-12-31",
    isCurrent: false,
    sortOrder: 0,
    fieldVisibility: { description: { public: false, pdf: false, docx: true } },
  },
  {
    sectionKey: "grants",
    title: "OPTIMIZE-TAVI — Balloon-Expandable vs Self-Expanding TAVI",
    subtitle: "NIHR-HTA-2018-1122",
    institution: "National Institute for Health Research — Health Technology Assessment",
    department: "",
    location: "United Kingdom",
    description: "£1,200,000",
    bullets:
      "Multicentre randomised controlled trial comparing balloon-expandable vs self-expanding TAVI valves\nCo-Investigator (UK lead site)\n5-year funding period (2019–2024)\n800 patients randomised across 8 countries",
    email: "",
    phone: "",
    startDate: "2019-04-01",
    endDate: "2024-03-31",
    isCurrent: false,
    sortOrder: 1,
    fieldVisibility: { description: { public: false, pdf: false, docx: true } },
  },
  {
    sectionKey: "grants",
    title: "AI-Assisted Coronary CTA for Pre-PCI Planning",
    subtitle: "KTP-2024-0891",
    institution: "Innovate UK — Knowledge Transfer Partnership",
    department: "",
    location: "United Kingdom",
    description: "£180,000",
    bullets:
      "Knowledge transfer partnership with AI imaging company to develop automated coronary CTA analysis for pre-PCI planning\nPrincipal Investigator\n2-year funding period (2024–2026)",
    email: "",
    phone: "",
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    isCurrent: true,
    sortOrder: 2,
    fieldVisibility: { description: { public: false, pdf: false, docx: true } },
  },

  // ── 30. Clinical Trials ──
  {
    sectionKey: "clinical_trials",
    title: "OPTIMIZE-TAVI Trial",
    subtitle: "ISRCTN 12345678 — Phase III RCT",
    institution: "Northbridge Heart Institute (Lead UK Site)",
    department: "Cardiovascular Research Unit",
    location: "London, United Kingdom",
    description:
      "Multicentre randomised controlled trial comparing balloon-expandable (Edwards SAPIEN 3) versus self-expanding (Medtronic Evolut R/PRO) transcatheter aortic valve implantation in intermediate surgical risk patients with severe aortic stenosis. Primary endpoint: all-cause mortality or disabling stroke at 12 months.",
    bullets:
      "800 patients randomised across 8 countries\nUK lead site — enrolled 120 patients\nPrimary results published in The Lancet 2023\n2-year follow-up presented at TCT 2023",
    email: "",
    phone: "",
    startDate: "2019-04-01",
    endDate: "2024-03-31",
    isCurrent: false,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "clinical_trials",
    title: "CORONARY-CT vs ICA — Imaging Strategy Trial",
    subtitle: "NCT 98765432 — Phase II RCT",
    institution: "Northbridge Heart Institute",
    department: "Cardiovascular Research Unit",
    location: "London, United Kingdom",
    description:
      "Randomised trial evaluating whether coronary CTA as first-line imaging (with downstream invasive coronary angiography as needed) is non-inferior to immediate invasive coronary angiography in patients presenting with stable chest pain. Primary endpoint: 12-month major adverse cardiovascular events.",
    bullets:
      "200 patients randomised\nRecruitment ongoing — 150/200 enrolled\nCo-Investigator\nFunded by Westland University Innovation Fund",
    email: "",
    phone: "",
    startDate: "2023-03-01",
    endDate: "2026-02-28",
    isCurrent: true,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 31. Research Projects ──
  {
    sectionKey: "research_projects",
    title: "AI-Assisted Coronary CTA Analysis for Pre-PCI Planning",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Cardiovascular Research Unit",
    location: "London, United Kingdom",
    description:
      "Collaborative project with HeartVision AI Ltd to develop and validate an artificial intelligence system for automated coronary artery segmentation, plaque characterisation, and lesion severity assessment on coronary CTA.",
    bullets:
      "Prospective validation study — 500 patients\nBlind comparison with invasive coronary angiography\nSensitivity 95%, specificity 89% for haemodynamically significant stenosis\nManuscript in preparation for JACC Cardiovascular Imaging",
    email: "",
    phone: "",
    startDate: "2024-01-01",
    endDate: "2025-12-31",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "research_projects",
    title: "Gender Disparities in Interventional Cardiology — UK National Audit",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Cardiovascular Research Unit",
    location: "London, United Kingdom",
    description:
      "Analysis of BCIS national audit data evaluating sex-based differences in access to, and outcomes from, percutaneous coronary intervention in the UK.",
    bullets:
      "Retrospective analysis of 1.2 million PCI procedures (2015–2023)\nIdentified significant gender gap in door-to-balloon time for women\nManuscript published in Heart 2024\nPresented at British Cardiovascular Society Annual Conference",
    email: "",
    phone: "",
    startDate: "2022-06-01",
    endDate: "2024-05-31",
    isCurrent: false,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 32. Publications ──
  {
    sectionKey: "publications",
    title: "Complex PCI in Elderly Patients: Insights from the COMPASS-PCI Registry",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Prospective multicentre study demonstrating that complex PCI in patients aged ≥75 years can be performed safely with comparable outcomes to younger patients when appropriate lesion selection and intravascular imaging are used.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 0,
    fieldVisibility: {},
    category: "Peer-Reviewed Original Research",
    authors:
      "Thompson M, Hartley SJ, Patel R, Nguyen T, Chen L, Williams D, O'Brien K, Singh A, Müller H, Dubois C, Garcia F, Lindqvist P, Rosseaux S, van der Berg J, Fitzgerald S, Murray E, Roberts T, Ashworth J, Blackwell C, Campbell D",
    journal: "European Heart Journal",
    volume: "45",
    issue: "12",
    pages: "1023–1035",
    doi: "10.1093/eurheartj/ehae123",
    pmid: "38456789",
    pmcid: "PMC12345678",
    startDate: "2024-03-15",
  },
  {
    sectionKey: "publications",
    title: "Balloon-Expandable versus Self-Expanding TAVI in Intermediate-Risk Patients: 2-Year Outcomes from the OPTIMIZE-TAVI Trial",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Two-year results of the OPTIMIZE-TAVI randomised controlled trial showing comparable mortality and stroke rates between balloon-expandable and self-expanding transcatheter heart valves.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 1,
    fieldVisibility: {},
    category: "Peer-Reviewed Original Research",
    authors:
      "Hartley SJ, Thompson M, Patel R, Dubois C, van der Berg J, Müller H, Garcia F, Nguyen T, Chen L, Williams D, O'Brien K, Singh A, Lindqvist P, Rosseaux S, Fitzgerald S, Murray E, Roberts T, Blackwell C, Campbell D, Ashworth J, Leung K, Hernandez M, Novak P, Sato T, Kim J",
    journal: "The Lancet",
    volume: "402",
    issue: "10405",
    pages: "887–899",
    doi: "10.1016/S0140-6736(23)01234-5",
    pmid: "37890123",
    pmcid: "PMC9876543",
    startDate: "2023-09-10",
  },
  {
    sectionKey: "publications",
    title: "Gender Disparities in Door-to-Balloon Time for ST-Elevation Myocardial Infarction: A UK National Audit Analysis",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Analysis of over 1.2 million PCI procedures from the BCIS national audit demonstrating persistent gender disparities in door-to-balloon time and procedural outcomes.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 2,
    fieldVisibility: {},
    category: "Peer-Reviewed Original Research",
    authors: "Thompson M, Williams D, O'Brien K, Roberts T",
    journal: "Heart",
    volume: "110",
    issue: "8",
    pages: "567–574",
    doi: "10.1136/heartjnl-2023-324567",
    pmid: "38123456",
    pmcid: "PMC11223344",
    startDate: "2024-01-20",
  },
  {
    sectionKey: "publications",
    title: "Intravascular Imaging-Guided PCI: A Systematic Review and Meta-Analysis of Randomised Controlled Trials",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Comprehensive meta-analysis of 28 randomised controlled trials (n=14,500) demonstrating significant mortality and target lesion revascularisation benefits of IVUS- and OCT-guided PCI compared with angiography-guided PCI.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 3,
    fieldVisibility: {},
    category: "Review Article",
    authors: "Thompson M, Singh A, Garcia F, Nguyen T",
    journal: "JACC Cardiovascular Interventions",
    volume: "17",
    issue: "3",
    pages: "201–215",
    doi: "10.1016/j.jcin.2023.11.012",
    pmid: "38234567",
    pmcid: "PMC11345678",
    startDate: "2024-02-01",
  },
  {
    sectionKey: "publications",
    title: "Transcatheter Aortic Valve Malpositioning — Lessons from 12 Consecutive Cases",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Case series describing causes, management, and outcomes of transcatheter aortic valve malpositioning from a single high-volume centre.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 4,
    fieldVisibility: {},
    category: "Case Report",
    authors: "Thompson M, Hartley SJ",
    journal: "Catheterization and Cardiovascular Interventions",
    volume: "103",
    issue: "2",
    pages: "E12–E20",
    doi: "10.1002/ccd.31234",
    pmid: "38345678",
    startDate: "2024-04-15",
  },
  {
    sectionKey: "publications",
    title: "Complex Coronary Intervention — A Practical Guide",
    subtitle: "2nd Edition",
    institution: "",
    department: "",
    location: "",
    description:
      "Comprehensive textbook covering the principles and practice of complex percutaneous coronary intervention, including CTO, left main, bifurcation, and calcified lesions. Second edition includes new chapters on intravascular lithotripsy and intravascular imaging.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 5,
    fieldVisibility: {},
    category: "Book",
    authors: "Thompson M, Hartley SJ (Editors)",
    journal: "",
    volume: "",
    issue: "",
    pages: "688 pages",
    doi: "10.1007/978-3-030-12345-6",
    startDate: "2023-06-01",
  },
  {
    sectionKey: "publications",
    title: "Intravascular Imaging in Complex PCI: IVUS, OCT, and Near-Infrared Spectroscopy",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Book chapter in 'Interventional Cardiology: Principles and Practice' (3rd Edition). Comprehensive review of intravascular imaging modalities and their applications in complex coronary intervention.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 6,
    fieldVisibility: {},
    category: "Book Chapter",
    authors: "Thompson M",
    journal: "",
    volume: "",
    issue: "",
    pages: "245–278",
    doi: "10.1007/978-3-030-98765-4_12",
    startDate: "2022-03-01",
  },
  {
    sectionKey: "publications",
    title: "TAVI in Bicuspid Aortic Valve Disease — Time to Embrace the Challenge?",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Editorial commentary on the evolving evidence base for transcatheter aortic valve implantation in patients with bicuspid aortic valve anatomy.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 7,
    fieldVisibility: {},
    category: "Editorial",
    authors: "Thompson M",
    journal: "European Heart Journal",
    volume: "44",
    issue: "22",
    pages: "2001–2003",
    doi: "10.1093/eurheartj/ehad456",
    startDate: "2023-06-01",
  },
  {
    sectionKey: "publications",
    title: "ESC/EACTS Guidelines on the Management of Valvular Heart Disease (2024 Update)",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Contributing author to the 2024 update of the European Society of Cardiology and European Association for Cardio-Thoracic Surgery guidelines on the management of valvular heart disease. Chapter: Transcatheter Aortic Valve Implantation.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 8,
    fieldVisibility: {},
    category: "Guideline",
    authors:
      "Vahanian A, Beyersdorf F, Praz F, Milojevic M, Baldus S, Bauersachs J, Capodanno D, Conradi L, De Bonis M, Ehlermann P, Frei U, Hindricks G, Jüni P, Lancellotti P, Lefèvre T, Lower C, Modine T, Ntalianis A, Ochsenkühn R, Pilgrim T, Prendergast B, Rosenhek R, Sabatier M, Sondergaard L, Tolan SP, Van Dyck D, Van Mieghem NM, von Bardeleben RS, von Eckardstein A, Wenaweser P, Windecker S, Zoghbi WA, Collet JP, Thiele H, Ottervanger JP, Capretti G, de Winter R, Eeckhout E, Geisler T, Hahn RT, Ibrahim R, Kim WK, Krasopoulos G, Laroche C, Luedike P, Makkar R, Meincke F, Mueller-Stolzenburg N, Neumann FJ, Ooms JFG, Otto CM, Petronio AS, Price S, Rodes-Cabau J, Rottbauer W, Rud士nk T, Schäfer U, Schiefer J, Schmitz-Rode T, Schönemann A, Schulz C, Thielmann M, Tzikas A, Van Es GA, Walther T, ZԌie boa T",
    journal: "European Heart Journal",
    volume: "45",
    issue: "40",
    pages: "4230–4320",
    doi: "10.1093/eurheartj/ehae567",
    startDate: "2024-08-25",
  },
  {
    sectionKey: "publications",
    title: "Temporal Trends in TAVI Utilisation and Outcomes in the UK: A 10-Year National Registry Analysis",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Retrospective analysis of the national TAVI registry demonstrating improving outcomes and expanding indications for transcatheter aortic valve implantation over a decade.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 9,
    fieldVisibility: {},
    category: "Peer-Reviewed Original Research",
    authors:
      "Thompson M, Patel R, Singh A, Williams D, O'Brien K, Roberts T, Blackwell C, Campbell D, Ashworth J",
    journal: "JACC Cardiovascular Interventions",
    volume: "16",
    issue: "18",
    pages: "2201–2212",
    doi: "10.1016/j.jcin.2023.07.045",
    pmid: "37989012",
    pmcid: "PMC10987654",
    startDate: "2023-09-25",
  },
  {
    sectionKey: "publications",
    title: "Left Atrial Appendage Closure in Patients with Atrial Fibrillation: A Practical Review",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Narrative review of current evidence, patient selection, procedural techniques, and outcomes for left atrial appendage occlusion in patients with non-valvular atrial fibrillation.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 10,
    fieldVisibility: {},
    category: "Review Article",
    authors: "Thompson M, Dubois C",
    journal: "Heart",
    volume: "109",
    issue: "15",
    pages: "1123–1131",
    doi: "10.1136/heartjnl-2022-322345",
    pmid: "37456789",
    startDate: "2023-07-15",
  },

  // ── 33. Reviews & Guidelines ──
  {
    sectionKey: "reviews_guidelines",
    title: "ESC/EACTS Guidelines on Valvular Heart Disease (2024 Update) — Contributing Author",
    subtitle: "",
    institution: "European Society of Cardiology / European Association for Cardio-Thoracic Surgery",
    department: "",
    location: "European Society of Cardiology",
    description:
      "Contributing author to the chapter on Transcatheter Aortic Valve Implantation in the 2024 ESC/EACTS guidelines. Provided evidence review, data synthesis, and recommendation development.",
    bullets:
      "Authored TAVI chapter with Prof. Bernard Prendergast\nReviewed 200+ references for evidence synthesis\nDeveloped 14 clinical recommendations with class/level of evidence\nGuideline published in European Heart Journal August 2024",
    email: "",
    phone: "",
    startDate: "2023-06-01",
    endDate: "2024-08-25",
    isCurrent: false,
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 34. Case Reports ──
  {
    sectionKey: "case_reports",
    title: "Transcatheter Aortic Valve-in-Valve for Failing Surgical Bioprosthesis with Coronary Obstruction Risk",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Interventional Cardiology",
    location: "London, United Kingdom",
    description:
      "Case report of a high-risk valve-in-valve TAVI in a patient with a failing surgical aortic bioprosthesis and high risk of coronary obstruction. Use of the BASILICA technique to prevent coronary obstruction.",
    bullets:
      "Patient: 82-year-old female with failing 23mm surgical bioprosthesis\nBASILICA technique performed to preserve coronary access\nSuccessful valve-in-valve deployment with good haemodynamic result\nPublished in Catheterization and Cardiovascular Interventions",
    email: "",
    phone: "",
    startDate: "2023-09-01",
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 35. Books ──
  {
    sectionKey: "books",
    title: "Complex Coronary Intervention — A Practical Guide",
    subtitle: "2nd Edition",
    institution: "",
    department: "",
    location: "",
    description:
      "688-page comprehensive textbook covering principles and practice of complex percutaneous coronary intervention. Published by Springer. Second edition (2023) includes new chapters on intravascular lithotripsy, intravascular imaging, and computational modelling. Used as primary reference in >40 interventional cardiology fellowship programmes worldwide.",
    bullets:
      "Published by Springer Nature, 2nd Edition (2023)\n688 pages, 32 chapters, 45 contributing authors\nTranslated into Mandarin Chinese and Japanese\nUsed in >40 fellowship programmes worldwide",
    email: "",
    phone: "",
    startDate: "2023-06-01",
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 36. Book Chapters ──
  {
    sectionKey: "book_chapters",
    title: "Intravascular Imaging in Complex PCI: IVUS, OCT, and Near-Infrared Spectroscopy",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Chapter 12 in 'Interventional Cardiology: Principles and Practice' (3rd Edition). Comprehensive review of intravascular imaging modalities and their applications in complex coronary intervention.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2022-03-01",
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "book_chapters",
    title: "TAVI in Bicuspid Aortic Valve Anatomy",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Chapter 8 in 'Structural Heart Interventions: A Clinical Guide' (1st Edition). Review of transcatheter aortic valve implantation in patients with bicuspid aortic valve anatomy, including pre-procedural planning, device selection, and procedural techniques.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2022-09-01",
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 37. Editorials & Commentaries ──
  {
    sectionKey: "editorials_commentaries",
    title: "TAVI in Bicuspid Aortic Valve Disease — Time to Embrace the Challenge?",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Invited editorial commentary in the European Heart Journal on the evolving evidence base for TAVI in bicuspid aortic valve anatomy.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2023-06-01",
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "editorials_commentaries",
    title: "Artificial Intelligence in Cardiovascular Imaging — Promise and Pitfalls",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Commentary in JACC Cardiovascular Imaging on the role of artificial intelligence in cardiovascular imaging, addressing validation challenges, regulatory pathways, and clinical integration.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2024-05-01",
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 38. Invited Lectures ──
  {
    sectionKey: "invited_lectures",
    title: "Complex PCI in 2024 — What's New and What Matters",
    subtitle: "Keynote Lecture",
    institution: "European PCR Congress",
    department: "",
    location: "Paris, France",
    description:
      "Invited keynote lecture at the annual EuroPCR congress. Reviewed the latest evidence on complex PCI techniques, intravascular imaging, and emerging technologies.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2024-05-22",
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "invited_lectures",
    title: "The Future of Structural Heart Interventions",
    subtitle: "Plenary Lecture",
    institution: "American College of Cardiology Annual Scientific Session",
    department: "",
    location: "Atlanta, United States",
    description:
      "Invited plenary lecture at ACC Annual Scientific Session. Discussed emerging transcatheter therapies, including tricuspid interventions, pulmonic valve replacement, and left ventricular support devices.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2024-04-07",
    sortOrder: 1,
    fieldVisibility: {},
  },
  {
    sectionKey: "invited_lectures",
    title: "Intravascular Imaging — The Case for Universal Adoption",
    subtitle: "Invited Lecture",
    institution: "British Cardiovascular Intervention Society Annual Conference",
    department: "",
    location: "Manchester, United Kingdom",
    description:
      "Invited lecture arguing for universal adoption of intravascular imaging in complex PCI. Presented meta-analysis data and single-centre outcomes.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2024-03-14",
    sortOrder: 2,
    fieldVisibility: {},
  },

  // ── 39. Conference Presentations ──
  {
    sectionKey: "conference_presentations",
    title: "Outcomes of Complex PCI in Octogenarians: Results from the COMPASS-PCI Registry",
    subtitle: "Oral Presentation",
    institution: "European Society of Cardiology Congress",
    department: "",
    location: "Barcelona, Spain",
    description:
      "Presented 12-month outcomes data from the COMPASS-PCI registry at the annual ESC Congress. Highlighted comparable outcomes between octogenarians and younger patients when appropriate lesion selection was applied.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2024-08-30",
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "conference_presentations",
    title: "TAVI in the Elderly: Real-World Evidence from a UK Centre",
    subtitle: "Poster Presentation",
    institution: "Transcatheter Cardiovascular Therapeutics (TCT)",
    department: "",
    location: "Washington, DC, United States",
    description:
      "Presented comparative outcomes data for TAVI in patients aged 80+ versus younger cohorts from a single high-volume UK centre.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2023-10-25",
    sortOrder: 1,
    fieldVisibility: {},
  },
  {
    sectionKey: "conference_presentations",
    title: "Gender Disparities in Door-to-Balloon Time: UK National Audit Analysis",
    subtitle: "Moderated Poster",
    institution: "British Cardiovascular Society Annual Conference",
    department: "",
    location: "Manchester, United Kingdom",
    description:
      "Presented analysis of BCIS national audit data showing persistent gender disparities in door-to-balloon time for STEMI in the UK.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2024-06-11",
    sortOrder: 2,
    fieldVisibility: {},
  },

  // ── 40. Patents ──
  {
    sectionKey: "patents",
    title: "Novel Coronary Artery Stent Design with Biodegradable Polymer Coating",
    subtitle: "UK Patent GB2598765",
    institution: "",
    department: "",
    location: "United Kingdom",
    description:
      "Patent for a novel coronary artery stent design featuring a biodegradable polymer coating eluting an anti-restenotic agent. Filed with the UK Intellectual Property Office.",
    bullets:
      "Filed: 2022-03-15\nGranted: 2023-09-01\nCo-inventors: Dr. Maya Thompson, Prof. James Hartley, Dr. David Williams\nCommercialisation through Westland University Technology Transfer Office",
    email: "",
    phone: "",
    startDate: "2022-03-15",
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 41. Awards ──
  {
    sectionKey: "awards",
    title: "Best Clinical Research Presentation",
    subtitle: "",
    institution: "British Cardiovascular Intervention Society Annual Conference",
    department: "",
    location: "Manchester, United Kingdom",
    description:
      "Awarded best oral presentation at the BCIS annual meeting for COMPASS-PCI interim results.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2023-03-14",
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "awards",
    title: "Fellow of the Year — Interventional Cardiology",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Interventional Cardiology",
    location: "London, United Kingdom",
    description:
      "Awarded Fellow of the Year during interventional cardiology fellowship for clinical excellence, research output, and contributions to the training programme.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2018-07-01",
    sortOrder: 1,
    fieldVisibility: {},
  },
  {
    sectionKey: "awards",
    title: "Sir William Osler Prize for Clinical Excellence",
    subtitle: "",
    institution: "Northbridge University",
    department: "Faculty of Medicine",
    location: "London, United Kingdom",
    description:
      "Awarded to the top-performing medical student in clinical examinations. Northbridge University.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2010-06-30",
    sortOrder: 2,
    fieldVisibility: {},
  },

  // ── 42. Memberships ──
  {
    sectionKey: "memberships",
    title: "Fellow — British Cardiovascular Intervention Society",
    subtitle: "FBCIS",
    institution: "BCIS",
    department: "",
    location: "United Kingdom",
    description:
      "Fellow since 2019. Active participant in national audit and quality improvement initiatives.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2019-01-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "memberships",
    title: "Member — European Society of Cardiology",
    subtitle: "",
    institution: "ESC",
    department: "",
    location: "European Society of Cardiology",
    description:
      "Active member since 2015. Attend annual congress and participate in working groups on interventional cardiology.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2015-01-01",
    isCurrent: true,
    sortOrder: 1,
    fieldVisibility: {},
  },
  {
    sectionKey: "memberships",
    title: "Fellow — European Society of Cardiology",
    subtitle: "FESC",
    institution: "ESC",
    department: "",
    location: "European Society of Cardiology",
    description:
      "Elected Fellow of the European Society of Cardiology for contributions to cardiovascular medicine.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2022-08-25",
    isCurrent: true,
    sortOrder: 2,
    fieldVisibility: {},
  },

  // ── 43. Society Leadership ──
  {
    sectionKey: "society_leadership",
    title: "Chair — BCIS Interventional Cardiology Programme Directors Committee",
    subtitle: "",
    institution: "British Cardiovascular Intervention Society",
    department: "",
    location: "United Kingdom",
    description:
      "Chair of the committee responsible for overseeing interventional cardiology training programmes across the UK. Developed national training standards and competency frameworks.",
    bullets:
      "Chair since 2022\nDeveloped national competency-based training framework\nOversee 24 training centres across the UK\nAnnual programme director workshops",
    email: "",
    phone: "",
    startDate: "2022-06-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "society_leadership",
    title: "Vice-Chair — ESC Working Group on Interventional Cardiology",
    subtitle: "",
    institution: "European Society of Cardiology",
    department: "Working Group on Interventional Cardiology",
    location: "European Society of Cardiology",
    description:
      "Vice-Chair of the ESC Working Group on Interventional Cardiology. Contribute to guideline development, educational programmes, and research initiatives.",
    bullets:
      "Vice-Chair since 2023\nOrganise annual Winter Meeting\nLead educational programme development\nCo-chair consensus document on intravascular imaging",
    email: "",
    phone: "",
    startDate: "2023-01-01",
    isCurrent: true,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 44. Editorial Boards ──
  {
    sectionKey: "editorial_boards",
    title: "Associate Editor — EuroIntervention",
    subtitle: "",
    institution: "EuroIntervention",
    department: "",
    location: "European Society of Cardiology",
    description:
      "Associate Editor for EuroIntervention journal. Handle peer review of submitted manuscripts, commission editorials, and contribute to journal strategy.",
    bullets:
      "Associate Editor since 2022\nHandle 80+ manuscripts per year\nCommission invited editorials and reviews\nContributed to journal impact factor growth strategy",
    email: "",
    phone: "",
    startDate: "2022-01-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "editorial_boards",
    title: "Editorial Board Member — JACC Cardiovascular Interventions",
    subtitle: "",
    institution: "Journal of the American College of Cardiology",
    department: "",
    location: "United States",
    description:
      "Member of the Editorial Board for JACC Cardiovascular Interventions. Review manuscripts and contribute to journal policy.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2021-06-01",
    isCurrent: true,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 45. Peer Review ──
  {
    sectionKey: "peer_review",
    title: "Regular Peer Reviewer",
    subtitle: "",
    institution:
      "European Heart Journal, JACC Cardiovascular Interventions, EuroIntervention, Heart, The Lancet, BMJ",
    department: "",
    location: "",
    description:
      "Regular reviewer for major cardiovascular journals. Review approximately 25 manuscripts per year. Recognised as exemplary reviewer by European Heart Journal (2023).",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2018-01-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 46. Grant Review ──
  {
    sectionKey: "grant_review",
    title: "Grant Reviewer — British Heart Foundation",
    subtitle: "",
    institution: "British Heart Foundation",
    department: "",
    location: "United Kingdom",
    description:
      "Regular grant reviewer for the British Heart Foundation. Review project grant applications and PhD fellowship applications.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2020-01-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "grant_review",
    title: "Grant Reviewer — National Institute for Health Research",
    subtitle: "",
    institution: "National Institute for Health Research",
    department: "",
    location: "United Kingdom",
    description:
      "Reviewer for NIHR Health Technology Assessment and Efficacy and Mechanism Evaluation programmes. Review clinical trial and health services research applications.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2021-06-01",
    isCurrent: true,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 47. Committee Service ──
  {
    sectionKey: "committee_service",
    title: "Cardiac Evaluation and Assessment Committee — NHS England",
    subtitle: "",
    institution: "NHS England",
    department: "",
    location: "United Kingdom",
    description:
      "Member of the cardiac assessment committee reviewing applications for new interventional cardiac services. Contribute to national service planning and configuration.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2022-09-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "committee_service",
    title: "Clinical Standards and Audit Committee — BCIS",
    subtitle: "",
    institution: "British Cardiovascular Intervention Society",
    department: "",
    location: "United Kingdom",
    description:
      "Committee member responsible for developing national clinical standards and audit specifications for interventional cardiology procedures.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2020-06-01",
    isCurrent: true,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 48. Community Service ──
  {
    sectionKey: "community_service",
    title: "Heart Health Awareness Programme — Local Schools",
    subtitle: "",
    institution: "Northbridge Heart Institute",
    department: "Community Engagement",
    location: "London, United Kingdom",
    description:
      "Lead the institute's community engagement programme delivering cardiovascular health awareness sessions in local schools. Reached 2,000+ students annually.",
    bullets:
      "Deliver annual heart health workshops to 15 local secondary schools\nTrain student health ambassadors in CPR and AED use\nOrganise annual 'Heart Health Week' at the institute\nMedia appearances promoting heart health awareness",
    email: "",
    phone: "",
    startDate: "2020-09-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 49. Global Health ──
  {
    sectionKey: "global_health",
    title: "Volunteer Interventional Cardiologist — Remote PCI Proctoring Programme",
    subtitle: "",
    institution: "International Cardiac Outreach Foundation",
    department: "",
    location: "Sub-Saharan Africa / South-East Asia",
    description:
      "Volunteer proctor for remote PCI training programme supporting interventional cardiology centres in low- and middle-income countries. Provide tele-mentoring and procedural guidance via live video link.",
    bullets:
      "Proctor 20+ complex PCI procedures annually via remote link\nSupport 3 partner centres in Kenya, Tanzania, and Vietnam\nDeveloped online PCI training curriculum in collaboration with WHO\nPresented at Global Health Conference 2023",
    email: "",
    phone: "",
    startDate: "2021-01-01",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "global_health",
    title: "Visiting Cardiologist — Peace of Mind Hospital",
    subtitle: "",
    institution: "Peace of Mind Hospital",
    department: "Cardiology",
    location: "Nairobi, Kenya",
    description:
      "Annual volunteer visit (2 weeks) to provide interventional cardiology services and training at a cardiac centre serving underprivileged populations.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2022-01-15",
    endDate: "2022-01-30",
    isCurrent: false,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 50. Media Engagement ──
  {
    sectionKey: "media_engagement",
    title: "Expert Commentator — BBC Radio 4 'Inside Health'",
    subtitle: "",
    institution: "BBC Radio 4",
    department: "",
    location: "United Kingdom",
    description:
      "Regular expert commentator on cardiovascular health topics for BBC Radio 4's Inside Health programme.",
    bullets:
      "3 appearances in 2023–2024 on topics including heart attacks in women, TAVI, and preventive cardiology\nReach audience of 2+ million listeners\nPromote evidence-based cardiovascular health messages",
    email: "",
    phone: "",
    startDate: "2023-01-15",
    isCurrent: true,
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 51. CME/CPD ──
  {
    sectionKey: "cme_cpd",
    title: "Advanced Structural Heart Disease Training",
    subtitle: "",
    institution: "European School of Cardiology",
    department: "",
    location: "Online / Attendance",
    description:
      "40 CPD credits. Comprehensive course on transcatheter valve therapies and structural heart interventions.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2023-06-01",
    endDate: "2023-06-30",
    isCurrent: false,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "cme_cpd",
    title: "Advanced Cardiac CT — Level 2 Maintenance",
    subtitle: "",
    institution: "Society of Cardiovascular Computed Tomography",
    department: "",
    location: "Online",
    description:
      "20 CPD credits. Maintenance of Level 2 cardiac CT certification.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2024-03-01",
    endDate: "2024-03-31",
    isCurrent: false,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 52. Courses & Workshops ──
  {
    sectionKey: "courses_workshops",
    title: "Complex PCI Workshop — CTO and Left Main Interventions",
    subtitle: "Course Director",
    institution: "Northbridge Heart Institute",
    department: "Interventional Cardiology",
    location: "London, United Kingdom",
    description:
      "Annual 3-day intensive workshop on complex PCI techniques including chronic total occlusions and left main interventions. Hands-on simulation and wet lab components.",
    bullets:
      "Course Director since 2022\n20 participants per year from 8 countries\nWet lab with porcine heart models\nSimulation-based CTO crossing techniques",
    email: "",
    phone: "",
    startDate: "2022-11-01",
    endDate: "2022-11-03",
    isCurrent: false,
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "courses_workshops",
    title: "TAVI Proctoring Workshop — New Centre Setup",
    subtitle: "Lead Proctor",
    institution: "Edwards Lifesciences",
    department: "",
    location: "Amsterdam, Netherlands",
    description:
      "Lead proctor for TAVI setup workshop supporting new centres establishing transcatheter aortic valve programmes.",
    bullets: "",
    email: "",
    phone: "",
    startDate: "2023-09-15",
    endDate: "2023-09-16",
    isCurrent: false,
    sortOrder: 1,
    fieldVisibility: {},
  },

  // ── 53. Languages ──
  {
    sectionKey: "languages",
    title: "English",
    subtitle: "Native",
    institution: "",
    department: "",
    location: "",
    description: "",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "languages",
    title: "French",
    subtitle: "Professional Working Proficiency",
    institution: "",
    department: "",
    location: "",
    description:
      "Professional working proficiency. Able to conduct clinical consultations, deliver lectures, and participate in francophone medical conferences.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 1,
    fieldVisibility: {},
  },
  {
    sectionKey: "languages",
    title: "Spanish",
    subtitle: "Conversational",
    institution: "",
    department: "",
    location: "",
    description:
      "Conversational proficiency. Basic medical Spanish for clinical communication during global health volunteering.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 2,
    fieldVisibility: {},
  },

  // ── 54. Digital Skills ──
  {
    sectionKey: "digital_skills",
    title: "Cardiovascular Imaging Software",
    subtitle: "Expert",
    institution: "",
    department: "",
    location: "",
    description:
      "TOMTEC 3D Echocardiography Analysis, TeraRecon Cardiac CT Post-Processing, CAAS (Pie Medical) Coronary Analysis, HeartFlow FFRCT Analysis.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "digital_skills",
    title: "Intravascular Imaging Analysis",
    subtitle: "Expert",
    institution: "",
    department: "",
    location: "",
    description:
      "Philips IVUS and OCT analysis software, Abbott ILUMIEN OPTIS System, Boston Scientific differential co-rotational IVUS reconstruction.",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 1,
    fieldVisibility: {},
  },
  {
    sectionKey: "digital_skills",
    title: "Statistical & Research Software",
    subtitle: "Proficient",
    institution: "",
    department: "",
    location: "",
    description:
      "R (statistical analysis), SPSS, REDCap (electronic data capture), GraphPad Prism, EndNote (reference management), LaTeX (manuscript preparation).",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 2,
    fieldVisibility: {},
  },

  // ── 55. Volunteer Service ──
  {
    sectionKey: "volunteer_service",
    title: "Volunteer Cardiologist — Médecins du Monde",
    subtitle: "",
    institution: "Médecins du Monde",
    department: "",
    location: "Lesbos, Greece",
    description:
      "Volunteer cardiologist providing cardiovascular care to refugees and displaced persons on the Greek island of Lesbos. Two 2-week deployments.",
    bullets:
      "Provided cardiovascular assessments for 150+ refugees\nManaged acute cardiovascular presentations including MI and arrhythmias\nCollaborated with international medical team\nDeployments: 2019 and 2022",
    email: "",
    phone: "",
    startDate: "2019-09-01",
    endDate: "2019-09-14",
    isCurrent: false,
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 56. Professional Interests ──
  {
    sectionKey: "professional_interests",
    title: "Professional Interests",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Advancing interventional cardiology through evidence-based practice and innovative technologies\nImproving outcomes for elderly patients undergoing complex cardiac procedures\nReducing global disparities in access to cardiovascular interventions\nMentoring the next generation of interventional cardiologists\nIntegration of artificial intelligence into cardiovascular imaging and procedural planning",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 0,
    fieldVisibility: {},
  },

  // ── 57. References ──
  {
    sectionKey: "references",
    title: "Prof. Sir James Hartley",
    subtitle: "MD, PhD, FRCP, FACC, FESC",
    institution: "Northbridge Heart Institute",
    department: "Interventional Cardiology",
    location: "London, United Kingdom",
    description:
      "Consultant cardiologist and former programme director. Supervised PhD and fellowship training. Personal and academic mentor.",
    bullets: "",
    email: "secret-referee@example.com",
    phone: "+441234567890",
    sortOrder: 0,
    fieldVisibility: {
      email: { public: false, pdf: false, docx: true },
      phone: { public: false, pdf: false, docx: true },
    },
  },
  {
    sectionKey: "references",
    title: "Dr. Eleanor Chen",
    subtitle: "MD, FRCPC",
    institution: "Metropolitan General Hospital",
    department: "Internal Medicine",
    location: "Toronto, Canada",
    description:
      "Programme director during internal medicine residency. Academic and clinical mentor.",
    bullets: "",
    email: "e.chen@example.invalid",
    phone: "+1-416-555-0020",
    sortOrder: 1,
    fieldVisibility: {
      email: { public: false, pdf: false, docx: true },
      phone: { public: false, pdf: false, docx: true },
    },
  },
  {
    sectionKey: "references",
    title: "Dr. Pierre Dubois",
    subtitle: "MD, PhD, FESC",
    institution: "Hôpital Européen Georges-Pompidou",
    department: "Cardiology",
    location: "Paris, France",
    description:
      "Director of the structural heart programme. Supervised structural heart fellowship. Research collaborator.",
    bullets: "",
    email: "p.dubois@example.invalid",
    phone: "+33-1-555-0030",
    sortOrder: 2,
    fieldVisibility: {
      email: { public: false, pdf: false, docx: true },
      phone: { public: false, pdf: false, docx: true },
    },
  },

  // ── 58. Custom ──
  {
    sectionKey: "custom",
    title: "Selected Media Appearances",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "BBC Radio 4 Inside Health — 'Heart Attacks in Women' (March 2023)\nBBC Radio 4 Inside Health — 'Understanding TAVI' (November 2023)\nBBC World Service Health Check — 'Heart Disease Prevention' (January 2024)\nSky News — 'New TAVI Technology' expert commentary (June 2024)\nThe Guardian — 'AI in Healthcare' feature interview (August 2024)",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 0,
    fieldVisibility: {},
  },
  {
    sectionKey: "custom",
    title: "Selected Industry Consultancies",
    subtitle: "",
    institution: "",
    department: "",
    location: "",
    description:
      "Edwards Lifesciences — Consultant on next-generation transcatheter aortic valve design (2022–present)\nBoston Scientific — Advisory board for intravascular imaging platform development (2023–present)\nHeartVision AI Ltd — Clinical advisor for coronary CTA analysis AI system (2024–present)\nMedtronic — Consultant on structural heart device development (2021–2023)",
    bullets: "",
    email: "",
    phone: "",
    sortOrder: 1,
    fieldVisibility: {},
  },
]
