export type SectionGroup =
  | "identity"
  | "education"
  | "clinical"
  | "academic"
  | "research"
  | "recognition"
  | "development"

export type SortMode = "newest_first" | "oldest_first" | "manual"
export type SourceMode = "website" | "website_with_override" | "cv_only"

export interface SectionDef {
  key: string
  label: string
  atsHeading: string
  group: SectionGroup
  groupLabel: string
  sourceMode: SourceMode
  websiteSourceType?: string
  canAddCvOnly: boolean
  supportsBullets: boolean
  defaultSortMode: SortMode
  defaultPublicEnabled: boolean
  defaultPdfEnabled: boolean
  defaultDocxEnabled: boolean
  sensitive: boolean
}

export const SECTION_GROUPS: Record<SectionGroup, { label: string; sortOrder: number }> = {
  identity: { label: "Identity & Credentials", sortOrder: 0 },
  education: { label: "Education & Training", sortOrder: 1 },
  clinical: { label: "Clinical Career", sortOrder: 2 },
  academic: { label: "Academic & Teaching", sortOrder: 3 },
  research: { label: "Research & Scholarship", sortOrder: 4 },
  recognition: { label: "Recognition & Service", sortOrder: 5 },
  development: { label: "Development & Additional", sortOrder: 6 },
}

export const CV_SECTIONS: SectionDef[] = [
  // ── GROUP A: IDENTITY & CORE CREDENTIALS ──
  {
    key: "professional_identity",
    label: "Professional Identity & Contact",
    atsHeading: "Professional Identity",
    group: "identity",
    groupLabel: "Identity & Credentials",
    sourceMode: "website_with_override",
    websiteSourceType: "profile",
    canAddCvOnly: false,
    supportsBullets: false,
    defaultSortMode: "manual",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "executive_summary",
    label: "Professional / Executive Summary",
    atsHeading: "Professional Summary",
    group: "identity",
    groupLabel: "Identity & Credentials",
    sourceMode: "cv_only",
    canAddCvOnly: false,
    supportsBullets: false,
    defaultSortMode: "manual",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "current_clinical_appointments",
    label: "Current Clinical Appointments",
    atsHeading: "Current Appointments",
    group: "identity",
    groupLabel: "Identity & Credentials",
    sourceMode: "website_with_override",
    websiteSourceType: "experience",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "current_academic_appointments",
    label: "Current Academic Appointments",
    atsHeading: "Academic Appointments",
    group: "identity",
    groupLabel: "Identity & Credentials",
    sourceMode: "website_with_override",
    websiteSourceType: "experience",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "medical_licensure",
    label: "Medical Licensure & Registration",
    atsHeading: "Licensure",
    group: "identity",
    groupLabel: "Identity & Credentials",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: false,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: true,
  },
  {
    key: "board_certification",
    label: "Board Certification",
    atsHeading: "Board Certification",
    group: "identity",
    groupLabel: "Identity & Credentials",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "professional_certifications",
    label: "Professional / Clinical Certifications",
    atsHeading: "Professional Certifications",
    group: "identity",
    groupLabel: "Identity & Credentials",
    sourceMode: "website_with_override",
    websiteSourceType: "certification",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },

  // ── GROUP B: EDUCATION & MEDICAL TRAINING ──
  {
    key: "medical_education",
    label: "Medical Education",
    atsHeading: "Education",
    group: "education",
    groupLabel: "Education & Training",
    sourceMode: "website_with_override",
    websiteSourceType: "education",
    canAddCvOnly: false,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "other_degrees",
    label: "Other Academic Degrees",
    atsHeading: "Education",
    group: "education",
    groupLabel: "Education & Training",
    sourceMode: "website_with_override",
    websiteSourceType: "education",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "internship",
    label: "Internship",
    atsHeading: "Internship",
    group: "education",
    groupLabel: "Education & Training",
    sourceMode: "website_with_override",
    websiteSourceType: "education",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "residency",
    label: "Residency / Specialty Training",
    atsHeading: "Postgraduate Training",
    group: "education",
    groupLabel: "Education & Training",
    sourceMode: "website_with_override",
    websiteSourceType: "education",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "fellowship",
    label: "Fellowship / Subspecialty Training",
    atsHeading: "Fellowship",
    group: "education",
    groupLabel: "Education & Training",
    sourceMode: "website_with_override",
    websiteSourceType: "education",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "postdoctoral_training",
    label: "Postdoctoral / Research Training",
    atsHeading: "Postdoctoral Training",
    group: "education",
    groupLabel: "Education & Training",
    sourceMode: "website_with_override",
    websiteSourceType: "education",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "advanced_training",
    label: "Advanced Professional Training",
    atsHeading: "Advanced Training",
    group: "education",
    groupLabel: "Education & Training",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },

  // ── GROUP C: CLINICAL CAREER ──
  {
    key: "clinical_experience",
    label: "Clinical & Professional Experience",
    atsHeading: "Clinical Experience",
    group: "clinical",
    groupLabel: "Clinical Career",
    sourceMode: "website_with_override",
    websiteSourceType: "experience",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "clinical_expertise",
    label: "Clinical Expertise / Areas of Practice",
    atsHeading: "Clinical Expertise",
    group: "clinical",
    groupLabel: "Clinical Career",
    sourceMode: "website_with_override",
    websiteSourceType: "interest",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "manual",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "procedures_skills",
    label: "Procedures / Technical Clinical Skills",
    atsHeading: "Procedures and Technical Skills",
    group: "clinical",
    groupLabel: "Clinical Career",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "manual",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "hospital_appointments",
    label: "Hospital / Institutional Appointments",
    atsHeading: "Hospital Appointments",
    group: "clinical",
    groupLabel: "Clinical Career",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "quality_improvement",
    label: "Quality Improvement",
    atsHeading: "Quality Improvement",
    group: "clinical",
    groupLabel: "Clinical Career",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "clinical_audit",
    label: "Clinical Audit",
    atsHeading: "Clinical Audit",
    group: "clinical",
    groupLabel: "Clinical Career",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "patient_safety",
    label: "Patient Safety / Clinical Governance",
    atsHeading: "Patient Safety and Clinical Governance",
    group: "clinical",
    groupLabel: "Clinical Career",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "leadership",
    label: "Leadership & Administrative Experience",
    atsHeading: "Leadership and Administrative Experience",
    group: "clinical",
    groupLabel: "Clinical Career",
    sourceMode: "website_with_override",
    websiteSourceType: "experience",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },

  // ── GROUP D: ACADEMIC MEDICINE & TEACHING ──
  {
    key: "academic_appointments",
    label: "Academic / Faculty Appointments",
    atsHeading: "Academic Appointments",
    group: "academic",
    groupLabel: "Academic & Teaching",
    sourceMode: "website_with_override",
    websiteSourceType: "experience",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "teaching_experience",
    label: "Teaching Experience",
    atsHeading: "Teaching Experience",
    group: "academic",
    groupLabel: "Academic & Teaching",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "curriculum_leadership",
    label: "Curriculum / Education Leadership",
    atsHeading: "Curriculum and Education Leadership",
    group: "academic",
    groupLabel: "Academic & Teaching",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "mentoring",
    label: "Mentoring & Supervision",
    atsHeading: "Mentoring and Supervision",
    group: "academic",
    groupLabel: "Academic & Teaching",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },

  // ── GROUP E: RESEARCH & SCHOLARSHIP ──
  {
    key: "research_experience",
    label: "Research Experience",
    atsHeading: "Research Experience",
    group: "research",
    groupLabel: "Research & Scholarship",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "research_interests",
    label: "Research / Scholarly Interests",
    atsHeading: "Research Interests",
    group: "research",
    groupLabel: "Research & Scholarship",
    sourceMode: "cv_only",
    canAddCvOnly: false,
    supportsBullets: true,
    defaultSortMode: "manual",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "grants",
    label: "Grants & Funded Projects",
    atsHeading: "Grants and Funded Projects",
    group: "research",
    groupLabel: "Research & Scholarship",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: false,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "clinical_trials",
    label: "Clinical Trials",
    atsHeading: "Clinical Trials",
    group: "research",
    groupLabel: "Research & Scholarship",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "research_projects",
    label: "Research Projects",
    atsHeading: "Research Projects",
    group: "research",
    groupLabel: "Research & Scholarship",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "publications",
    label: "Publications",
    atsHeading: "Publications",
    group: "research",
    groupLabel: "Research & Scholarship",
    sourceMode: "website_with_override",
    websiteSourceType: "publication",
    canAddCvOnly: false,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "reviews_guidelines",
    label: "Reviews / Guidelines / Consensus Statements",
    atsHeading: "Reviews and Guidelines",
    group: "research",
    groupLabel: "Research & Scholarship",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "case_reports",
    label: "Case Reports / Technical Notes",
    atsHeading: "Case Reports",
    group: "research",
    groupLabel: "Research & Scholarship",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "books",
    label: "Books",
    atsHeading: "Books",
    group: "research",
    groupLabel: "Research & Scholarship",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "book_chapters",
    label: "Book Chapters",
    atsHeading: "Book Chapters",
    group: "research",
    groupLabel: "Research & Scholarship",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "editorials_commentaries",
    label: "Editorials / Commentaries / Letters",
    atsHeading: "Editorials and Commentaries",
    group: "research",
    groupLabel: "Research & Scholarship",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "invited_lectures",
    label: "Invited Lectures",
    atsHeading: "Invited Lectures",
    group: "research",
    groupLabel: "Research & Scholarship",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "conference_presentations",
    label: "Conference Presentations",
    atsHeading: "Presentations",
    group: "research",
    groupLabel: "Research & Scholarship",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "patents",
    label: "Patents / Innovation",
    atsHeading: "Patents",
    group: "research",
    groupLabel: "Research & Scholarship",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },

  // ── GROUP F: RECOGNITION & PROFESSIONAL SERVICE ──
  {
    key: "awards",
    label: "Awards / Honors / Distinctions",
    atsHeading: "Awards and Honors",
    group: "recognition",
    groupLabel: "Recognition & Service",
    sourceMode: "website_with_override",
    websiteSourceType: "achievement",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "memberships",
    label: "Professional Memberships & Fellowships",
    atsHeading: "Professional Memberships",
    group: "recognition",
    groupLabel: "Recognition & Service",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "manual",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "society_leadership",
    label: "Professional Society Leadership",
    atsHeading: "Professional Society Leadership",
    group: "recognition",
    groupLabel: "Recognition & Service",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "editorial_boards",
    label: "Editorial Boards",
    atsHeading: "Editorial Boards",
    group: "recognition",
    groupLabel: "Recognition & Service",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "peer_review",
    label: "Journal Peer Review",
    atsHeading: "Peer Review",
    group: "recognition",
    groupLabel: "Recognition & Service",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "grant_review",
    label: "Scientific / Grant Review Service",
    atsHeading: "Grant Review Service",
    group: "recognition",
    groupLabel: "Recognition & Service",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "committee_service",
    label: "Institutional / Hospital Committee Service",
    atsHeading: "Committee Service",
    group: "recognition",
    groupLabel: "Recognition & Service",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "community_service",
    label: "Community / Public Service",
    atsHeading: "Community Service",
    group: "recognition",
    groupLabel: "Recognition & Service",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "global_health",
    label: "Global Health",
    atsHeading: "Global Health",
    group: "recognition",
    groupLabel: "Recognition & Service",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "media_engagement",
    label: "Media / Public Engagement",
    atsHeading: "Media and Public Engagement",
    group: "recognition",
    groupLabel: "Recognition & Service",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },

  // ── GROUP G: CONTINUING DEVELOPMENT & ADDITIONAL ──
  {
    key: "cme_cpd",
    label: "CME / CPD",
    atsHeading: "Continuing Medical Education",
    group: "development",
    groupLabel: "Development & Additional",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "courses_workshops",
    label: "Courses / Workshops",
    atsHeading: "Courses and Workshops",
    group: "development",
    groupLabel: "Development & Additional",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "languages",
    label: "Languages",
    atsHeading: "Languages",
    group: "development",
    groupLabel: "Development & Additional",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "manual",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "digital_skills",
    label: "Digital / Research / Technical Skills",
    atsHeading: "Technical Skills",
    group: "development",
    groupLabel: "Development & Additional",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "manual",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "volunteer_service",
    label: "Volunteer Service",
    atsHeading: "Volunteer Service",
    group: "development",
    groupLabel: "Development & Additional",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "newest_first",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "professional_interests",
    label: "Professional Interests",
    atsHeading: "Professional Interests",
    group: "development",
    groupLabel: "Development & Additional",
    sourceMode: "website_with_override",
    websiteSourceType: "interest",
    canAddCvOnly: false,
    supportsBullets: true,
    defaultSortMode: "manual",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
  {
    key: "references",
    label: "References",
    atsHeading: "References",
    group: "development",
    groupLabel: "Development & Additional",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: false,
    defaultSortMode: "manual",
    defaultPublicEnabled: false,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: true,
  },
  {
    key: "custom",
    label: "Custom Sections",
    atsHeading: "Additional Information",
    group: "development",
    groupLabel: "Development & Additional",
    sourceMode: "cv_only",
    canAddCvOnly: true,
    supportsBullets: true,
    defaultSortMode: "manual",
    defaultPublicEnabled: true,
    defaultPdfEnabled: true,
    defaultDocxEnabled: true,
    sensitive: false,
  },
]

export const CV_SECTION_KEYS = CV_SECTIONS.map((s) => s.key)

export const SECTION_KEY_SET = new Set(CV_SECTION_KEYS)

export function getSectionDef(key: string): SectionDef | undefined {
  return CV_SECTIONS.find((s) => s.key === key)
}

export function getSectionsByGroup(group: SectionGroup): SectionDef[] {
  return CV_SECTIONS.filter((s) => s.group === group)
}

export const PRESETS: Record<string, { label: string; description: string; defaultOrder: string[] }> = {
  international_physician: {
    label: "International Physician",
    description: "Balanced general-purpose physician CV for international applications",
    defaultOrder: [
      "professional_identity", "executive_summary",
      "current_clinical_appointments", "current_academic_appointments",
      "medical_licensure", "board_certification", "professional_certifications",
      "medical_education", "other_degrees", "residency", "fellowship",
      "clinical_experience", "clinical_expertise", "procedures_skills",
      "leadership", "research_experience", "publications",
      "conference_presentations", "invited_lectures",
      "awards", "memberships", "committee_service",
      "teaching_experience", "cme_cpd", "languages", "digital_skills",
      "references",
    ],
  },
  clinical_consultant: {
    label: "Clinical / Consultant",
    description: "Clinical credentials, licensure, and leadership prioritized",
    defaultOrder: [
      "professional_identity", "executive_summary",
      "current_clinical_appointments",
      "medical_licensure", "board_certification", "professional_certifications",
      "medical_education", "residency", "fellowship",
      "clinical_experience", "clinical_expertise", "procedures_skills",
      "hospital_appointments", "leadership",
      "quality_improvement", "clinical_audit", "patient_safety",
      "teaching_experience", "memberships", "cme_cpd",
      "publications", "awards", "references",
    ],
  },
  academic_faculty: {
    label: "Academic Faculty",
    description: "Education, appointments, research, teaching, and publications prioritized",
    defaultOrder: [
      "professional_identity", "executive_summary",
      "medical_education", "other_degrees", "residency", "fellowship", "postdoctoral_training",
      "academic_appointments", "current_academic_appointments",
      "teaching_experience", "curriculum_leadership", "mentoring",
      "research_experience", "research_interests", "grants",
      "publications", "reviews_guidelines", "case_reports", "books", "book_chapters", "editorials_commentaries",
      "invited_lectures", "conference_presentations",
      "awards", "memberships", "editorial_boards", "peer_review", "grant_review",
      "committee_service", "cme_cpd", "references",
    ],
  },
  physician_scientist: {
    label: "Physician-Scientist / Research",
    description: "Research, grants, trials, and publications prioritized",
    defaultOrder: [
      "professional_identity", "executive_summary",
      "medical_education", "residency", "fellowship", "postdoctoral_training",
      "research_experience", "research_interests",
      "grants", "clinical_trials", "research_projects",
      "publications", "reviews_guidelines", "case_reports", "books", "book_chapters",
      "invited_lectures", "conference_presentations", "patents",
      "academic_appointments", "teaching_experience", "mentoring",
      "awards", "memberships", "editorial_boards", "peer_review",
      "cme_cpd", "references",
    ],
  },
  early_career: {
    label: "Early Career / Residency-Fellowship",
    description: "Education, training, certifications, and research prioritized",
    defaultOrder: [
      "professional_identity", "executive_summary",
      "medical_education", "other_degrees", "internship", "residency", "fellowship",
      "board_certification", "professional_certifications",
      "clinical_experience", "clinical_expertise",
      "research_experience", "research_interests",
      "publications", "conference_presentations",
      "teaching_experience", "mentoring",
      "awards", "memberships", "cme_cpd", "languages",
      "volunteer_service", "references",
    ],
  },
  custom: {
    label: "Custom",
    description: "Fully customizable — Admin controls all section visibility and order",
    defaultOrder: CV_SECTION_KEYS,
  },
}

export function getPresetOrder(presetKey: string): string[] {
  const preset = PRESETS[presetKey]
  if (!preset) return CV_SECTION_KEYS
  const extra = CV_SECTION_KEYS.filter((k) => !preset.defaultOrder.includes(k))
  return [...preset.defaultOrder, ...extra]
}

export const SORT_MODE_LABELS: Record<SortMode, string> = {
  newest_first: "Newest First (Reverse Chronological)",
  oldest_first: "Oldest First (Chronological)",
  manual: "Manual Order",
}

export const SOURCE_MODE_LABELS: Record<SourceMode, string> = {
  website: "Using Website Data",
  website_with_override: "Using Website Data",
  cv_only: "CV-Only Content",
}
