ALTER TABLE "HomeSpotlightImage" ADD COLUMN "xPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "HomeSpotlightImage" ADD COLUMN "yPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "HomeSpotlightImage" ADD COLUMN "widthPercent" DOUBLE PRECISION NOT NULL DEFAULT 45;
ALTER TABLE "HomeSpotlightImage" ADD COLUMN "zIndex" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "HomeSpotlightImage" ADD COLUMN "mobileXPercent" DOUBLE PRECISION;
ALTER TABLE "HomeSpotlightImage" ADD COLUMN "mobileYPercent" DOUBLE PRECISION;
ALTER TABLE "HomeSpotlightImage" ADD COLUMN "mobileWidthPercent" DOUBLE PRECISION;
ALTER TABLE "HomeSpotlightImage" ADD COLUMN "mobileRotation" DOUBLE PRECISION;
ALTER TABLE "HomeSpotlightSetting" ALTER COLUMN "collageStyle" SET DEFAULT 'freeform';
